# Generated by Django 4.1.5 on 2023-01-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0002_alter_idea_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea", name="star", field=models.BooleanField(default=False),
        ),
    ]
